# Generated by Django 5.1.4 on 2024-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='app_name',
        ),
    ]
