# Generated by Django 5.1.4 on 2024-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='app_developers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
