# Generated by Django 5.1.4 on 2024-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_app_developers_review_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
